### ISSUE TITLE
Source map file not being created

### ISSUE THREAD

**Issue by joneal** [princed/grunt-csswring#6]
Not sure if I am doing something wrong, but I have tried various combinations and cannot get a csswring to create a source map for one of my csswring tasks.

GruntFile:

csswring: {
            options: {
                removeAllComments: true,
                map: true
            },

            cssApp: {               
                src: '<%= meta.cssPath%>/site.css',
                dest: '<%= meta.resPath %>/_app.css'
            },

            cssglobal: {               
                src: [
                    '<%= meta.cssPath%>/bootstrap.css',
                    '<%= meta.cssPath%>/ng-grid.css'
                ],
                dest: '<%= meta.resPath %>/_cssglobal.css'
            }            
        },

Output:
C:\!samtec\Training\WebTech\WebTechTest2Solution\WebTechLab2.Web\_build>grunt
Running "csswring:cssApp" (csswring) task
File ../_resources/_app.css created: 31 B → 18 B

Running "csswring:cssglobal" (csswring) task
File ../_resources/_cssglobal.css created: 141.83 kB → 117.03 kB
File ../_resources/_cssglobal.css.map created (source map).

I can never get a source map created for _app.css.   Any suggestions?

**Comment by BrianLenzo** [comment]
I cannot get csswring to generate any sourcemaps at all.  I have a simple config

options: {
                removeAllComments: true,
                map: true
},
minify: {
                src: 'target/build/paychex.framework.core.ui/css/paychex-ui.css',
                dest: 'target/build/paychex.framework.core.ui/css/paychex-ui.min.css' 
}

Console output:
Running "csswring:minify" (csswring) task
File target/build/paychex.framework.core.ui/css/paychex-ui.min.css created: 8.79 kB → 6.69 kB

**Comment by princed** [comment]
There was a silly bug, sorry for delay :(
Try 1.1.1 please.
